### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by JesperBllnbm**
Hello,

as you suggested I started to implement a dark mode. I also added a few more customisation options. I think the map center button should be optional (which is not yet implemented). Also I think the satellite view is not necessary when custom map styles are possible. 
Unknown-4
Happy to discuss the changes :)

### CODE REVIEW

**Comment by humazed** [comment]
Thanks for the PR, it's late here now, will check it tomorrow morning.

**Comment by humazed** [comment]
your edits break the light mode working on fixing it before release

**Comment by JesperBllnbm** [comment]
Sorry to hear this. I fixed it: 
https://github.com/JesperBllnbm/google_map_location_picker/commit/ea79492ebf723fff8eafd3fcc8866fa194c5b0b8

**Comment by humazed** [comment]
I have already fixed it and since flutter `1.12.13` is now stable I think I will add `extendBodyBehindAppBar` to this release and since the UI changes are big I think it would be a good idea to release it as 3.0.0

can you download the latest version of the code and tell me what you think of the light mode and if you have any suggestions before the release.

**Comment by JesperBllnbm** [comment]
> I have already fixed it, sorry that I haven't updated my comment.
> and since flutter `1.12.13` is now stable I think I will add `extendBodyBehindAppBar` to this release and since the UI changes are big I think it would be a good idea to release it as 3.0.0
> 
> can you download the latest version of the code and tell me what you think of the light mode and if you have any suggestions before the release.

Hi, 

from a UX perspective it is a little bit odd that every icon button is white in light mode (they should be black) but the back button in the appBar. Also in dark mode all the icons should be white. I fixed this in my last commit. I had to pass the iconTheme to the appBar to achieve this. I would also keep the searchBar white when the light mode is enabled and no custom settings are passed. I like the possibility to disable and enable the map buttons. Also I wanted to suggest that we could add a headerWidget for the resultCard, I think in an app where you need to pick multiple locations it is helpful to remind the user which location they are picking right now.

Thanks for keeping me in the loop!

**Comment by humazed** [comment]
> from a UX perspective it is a little bit odd that every icon button is white in light mode (they should be black) 
I agree
Screenshot_1576234458

> I like the possibility to disable and enable the map buttons
They are configurable now with 
`myLocationButtonEnabled`
`layersButtonEnabled`


>I wanted to suggest that we could add a headerWidget for the resultCard
this could a good feature but I'm not sure which place is the best for placing the header.
I have seen your solution and I think it doesn't look good.
Screenshot_1576234699

I will test it a little more and if everything is ok will release it as 3.0.0

**Pull request merged**
